# This file was generated by GoReleaser. DO NOT EDIT.
class GenLgtm < Formula
  desc "Convert your favorite images to LGTM images."
  homepage "https://github.com/8398a7/gen-lgtm"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "http://github.com/8398a7/gen-lgtm/releases/download/v1.0.0/gen-lgtm_darwin_amd64.tar.gz"
    sha256 "dc4b3006da82b6d628dd68645a73682c5b7ba39731007fcfdd35fe1640b18b3c"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "http://github.com/8398a7/gen-lgtm/releases/download/v1.0.0/gen-lgtm_linux_amd64.tar.gz"
      sha256 "ca78a461b8f90208a63108f81296ac1fbfade3bd6ecfc8785f3902405fa77a1c"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "http://github.com/8398a7/gen-lgtm/releases/download/v1.0.0/gen-lgtm_linux_arm64.tar.gz"
        sha256 "c15e540f4fa39e633034113be1f8549ac90e39b4c6f5e5d33c0b9ca80bf35552"
      else
      end
    end
  end

  def install
    bin.install "gen-lgtm"
  end
end
